### ISSUE TITLE
Add password protection support

### ISSUE THREAD

**Issue by Hedwig7s** [krissrex/google-authenticator-exporter#12]
Having the app freely available to anyone on your computer is a security hazard

**Comment by krissrex** [comment]
I'm not sure I understand you.
What app, this code?

Yes, you should delete the files and secrets when you are done exporing.

I will not encrypt the output from this program, because you need the results in cleartext when migrating into other authenticator applications.

I could print a reminder at the end, however, with a warning to remove the files after the user is done.

**Comment by Hedwig7s** [comment]
> I'm not sure I understand you. What app, this code?
> 
> Yes, you should delete the files and secrets when you are done exporting.
> 
> I will not encrypt the output from this program, because you need the results in cleartext when migrating into other authenticator applications.
> 
> I could print a reminder at the end, however, with a warning to remove the files after the user is done.

Add the ability to have a prompt for a password/pin when opening the app

**Comment by mrambossek** [comment]
> Add the ability to have a prompt for a password/pin when opening the app

what app? what you are saying doesnt make sense?

**Comment by krissrex** [comment]
The sensitive data is the QR, your URI from the QR, and the outputs (text or QR images) from this application.
Running the application itself does not expose any secret data.
